# Generated by Django 4.1.1 on 2022-09-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_brand_name_alter_color_name_alter_size_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_url',
            field=models.URLField(max_length=512),
        ),
    ]
