# Generated by Django 4.1.1 on 2022-10-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_color_hex_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_ua',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AddField(
            model_name='product',
            name='title_ua',
            field=models.CharField(default='', max_length=255),
        ),
    ]
