# Generated by Django 4.1.1 on 2022-10-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_product_description_ua_product_title_ua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title_ua',
            field=models.CharField(default='', max_length=355),
        ),
    ]
