# Generated by Django 4.1.1 on 2022-10-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_product_title_ua'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_ua',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='color',
            name='name_ua',
            field=models.CharField(default='', max_length=50),
        ),
    ]
